- docs/working-with-github.md
> working-with-github.md

- repo/mk/js.deps.private.mk
Problem:
~/gs-client$ make node_modules_private
make: Entering directory '/Users/tobiaslindgren/git/firecloud/gs-client'
bash: DEPS: unbound variable
make: *** [support-firecloud/repo/mk/js.deps.private.mk:49: node_modules_private] Error 1
> Fixed problem with DEPS: unbound variable

- ci/darwin/bootstrap
> Fixed bug in bootstrap with brew info

- bin/aws-iam-login.inc.sh
> Fix Zsh support in aws-iam-login.inc.sh

- ci/darwin/bootstrap
- ci/linux/bootstrap
- repo/dot.editorconfig
- repo/dot.travis.sh.sf
- repo/mk/js.deps.npm.mk
- repo/mk/py.check.flake.mk
- repo/mk/py.common.mk
- repo/mk/py.deps.pipenv.mk
> support python via pipenv

- bin/aws-iam-login.inc.sh
Adding a function that can help with executing templates
which require credentials in other accounts e.g. env-route stacks
The function will take the essential AWS env vars and store them in
namespaced (prefixed) env vars.
> aws-iam-login-ns

- repo/mk/js.publish.npg.mk
- repo/mk/js.publish.tag.mk
~**NOT TESTED**~
tested manually
> create a merge commit when upstream diverges before/during release

- .travis.yml
- Brewfile.inc.sh
theory: faster because packages should be more up-to-date
> try using linux xenial 16.04

- doc/working-with-git-new.md
https://github.com/tobiipro/support-firecloud/pull/61#issuecomment-448604637
> docs: increased protection for master branch

- repo/mk/generic.misc.promote-tag-to-env-branch.mk
Intended flow
* `make promote/prod/v0.0.100`
* get presented with the 'git log' (simple, oneline per commit) of changes to be promoted from v0.0.99 to v0.0.100
* get asked if the user wants to continue
* do the promoting via travis, if the user didn't say cancel at the previous question
> show promotion log

- repo/dot.gitignore.node
- repo/mk/core.build.mk
- repo/mk/generic.common.mk
- repo/mk/js.common.mk
- repo/mk/py.common.mk
> add BUILD and VERSION targets

- repo/mk/core.common.mk
> nuking should also happen in submodules. fix #87

- repo/mk/core.common.mk
> 'make nuke': git-clean instead of git-stash

- doc/travis-ci.md
> update docs about preferred way to handle encrypted env vars in travis ci

- ci/brew-install-basic.inc.sh
> add retry as a basic brew dep

- doc/how-to-release.md
- doc/travis-ci.md
* Fixes:
---
@andreineculau, feel free to do changes as necessary to make this go faster. Thanks!
> update on travis-ci docs. Fixes #100

- sh/app-env.ci.inc.sh
* Fixes: https://github.com/tobiipro/atex-platform/issues/111
---
> move teardown check to *-env case

- repo/mk/js.publish.npg.mk
- repo/mk/js.publish.tag.mk
* Fixes: #104
---
I don't understand why I made it so complex the first time with commit-tree... 🤦‍♂️
> fix 'make release' undoing changes

- repo/mk/js.deps.npm.mk
> check that changes via npm-install-peer-dependencies are committed

- bin/.editorconfig
- bin/aws-cloudformation-create-stack-policy
- repo/cfn/inc.mk
* Fixes:
---
Will need to go into atex-platform and atex-consumer-sov and remove duplicate stuff from there after update.
> Add CFN Policy Support

- repo/mk/js.deps.npm.mk
* Fixes:
---
with this change, a project using angular-cli that wants `tslint@~5.11.0` but uses tslint-config-firecloud which wants `tslint@^5.16.0` will be able to run a successful `make deps-npm` while catching (failing) other unmet peer deps
marked as bugfix since the current situation of allowing any unmet peer deps is undesirable
> allow 'make deps-npm' to handle known unmet peer deps

- repo/dot.vscode/extensions.json
> recommend vscode extension for jest

- repo/cfn/inc.mk
- repo/mk/core.clean.mk
- repo/mk/core.common.mk
* Refs: #98 
---
(some name cleaning sneaked in)
> make it easy to clean cfn artifacts. ref #98

- sh/app.inc.sh
* Fixes: #56 
---
I believe this is as far as #56 goes.
> notify slack on cfn drifts

- repo/mk/js.check.eslint.mk
> eslint also executables with a node shebang

- repo/dot.ci.sh.sf
> de-transcrypt also in PRs from the same repo

- repo/dot.vscode/settings.json
VSCode (v 1.41.1) show this dialog when opening a repo with support-firecloud
> Updated vscode settings.json file due to automatic migration change for eslint/Code

- .travis.yml
> Validate travis

- doc/how-to-release.md
- repo/Makefile.node
The generated makefile pointed to the wrong mk file in the support-firecloud/repo/mk.
> update references in node project bootstrap script

- ci/brew-bootstrap.inc.sh
Improve informational message when brew executable is not found during bootstrap.
> Improve bootstap message when brew is not found.

- ci/brew-install-aws.inc.sh
* Fixes: #150 
---
read through the breaking changes, and deployed successfully 1 backend & 1 frontend
> allow awscli v2, in addition to v1

- sh/app.inc.sh
> Move some exports that crashes runtime if const.inc hasnt been sourced yet

- .travis.yml
- Brewfile.inc.sh
- ci/brew-bootstrap.inc.sh
- ci/brew-util.inc.sh
- ci/darwin/bootstrap
- sh/exe.inc.sh
Pull request to trigger build.
> Add more logging to darwin bootstrap and hide ridicolously long list of formulaes from "brew update".

- ci/linux/bootstrap-sudo
* Fixes:
---
Implementing @spschlegel 's fix to the hashsum mismatch problem found on the linux builds.
> clean var lib apt lists before update

- ci/brew-install-node.inc.sh
* Fixes:
---
While porting nvm functionality in #182 I also bumped into other "small" fixes, which might be good to port, especially the "don't change working directory" fix.
> Node bootstrap fixes

- repo/mk/js.deps.npm.mk
* Fixes:
---
Context: when lodash-firecloud [0.5.25](https://github.com/tobiipro/lodash-firecloud/commit/e77416d277b4a3c951b218d9949efe4f04a924c5) was released, projects with a `package-lock.json` noticed a failure triggered by `make deps` where package-lock.json was being modified with
```diff
-        "@types/lodash": "^4.14.129",
+        "@types/lodash": "4.14.160",
```
This has been tracked down to running `npm remove --save(-prod) smth-that-doesnt-exist` which seems to trigger a bug in `npm`.
This PR removes the "hack" of using `npm remove` to sort dependencies and instead uses `jq` to do that. The intention is that the exact same things (keys of `dev/dependencies`) are being sorted, in the same way as before, without any other changes to package.json as …
> sort dependencies without 'npm remove' hack

- ci/brew-install-node.nvm.inc.sh
* Fixes:
---
Following #182 , we thought we are installing a `node` version based on `.nvmrc` and that we are also installing the same `npm` version as the one installed on the system (i.e. the latest `npm` at the time of the bootstrap procedure = at the time of the docker-image building) by running `nvm reinstall`
The alignment of `npm` versions is important because of breaking changes that are introduced in npm 6.6 that adds "optional:true" in `package-lock.json`, something that is removed by e.g. `npx npm@6.5 install`. See https://stackoverflow.com/questions/54411377/package-lock-json-file-package-with-optional-true
After too much debugging, I learned that
1. `nvm` doesn't let you update `npm`, thus you need a workaround https://muffinman.io/nvm-updating-npm/
2. …
> fix upgrading npm under nvm

- repo/ci.sh/env.github-actions.inc.sh
> Remove string in regex comparison
